### ISSUE TITLE
Connection always refused or times out

### ISSUE THREAD

**Issue by wblamkin** [Qirky/Troop#12]
Hi, I'm attempting to use Troop with FoxDot, however, I'm running into trouble attempting to connect a client from one computer to a server on another. I have SuperCollider listening to FoxDot on both computers, and am able to connect a client to server as long as it's on the same computer. When attempting to connect a client to a server that's on a different computer and IP address, I am either met with Error 61, connection refused, or Error 60, connection timed out.

As for things I've tried to troubleshoot already, I've turned off the firewall on both computers in case that was preventing any kind of access between them, had them connect to different Wifi networks in case the IP addresses were getting confused, and double checked to make sure the IP address and port number was correct whenever attempting to connect (which never displayed as 127.0.01 as the troubleshooting section on the Troop page suggested to check).

Any help would be appreciated! I am excited about the prospect of using Troop for projects but am frustrated with it at the moment. Thanks in advance.

**Comment by Qirky** [comment]
Hmm, it seems like a network issue as opposed to Troop - what operating system are you using? If it's Windows be wary of using Home Groups as that has messed things up for me in the past

**Comment by wblamkin** [comment]
Both the computers I'm trying to use are running Mac OS X High Sierra.

**Comment by Qirky** [comment]
Ok, are you able to "ping" the computer with the Troop server on from the client, and vice versa?

**Comment by wblamkin** [comment]
I'm not exactly sure what that means, how would I go about doing that?

**Comment by Qirky** [comment]
There's a `ping` command you can run from the terminal which basically sends a message to another computer over a network and times how long it takes to get a response. It's just `ping <ip address>`. To get the IP address of a computer you can run `ifconfig` in the terminal, which will display your IP address (running the Troop server should also do that as well). If get error messages when using `ping` then there's an issue with the network, if not then it could be an issue with Troop

**Comment by wblamkin** [comment]
I've discovered it is an issue with networking. The ping command keeps requesting timeouts. this might be an issue with my computers' remote settings/firewall that I'll have to dig into.... Glad to know it's not an issue with Troop. Are you aware of the specific setting I would need to change to let this happen? If not I'll do research. Thank you for your help!

**Comment by Qirky** [comment]
Hi sorry for the *very* late reply - did you manage to solve this? I don't know much about the specifics of Mac OS but I would probably try turning the firewall off and testing `ping`. If you get a response then you know its likely the firewall. I've had issues with people being on different subnets of the same network via windows HomeGroup (i.e. some people in it, some people not but everyone is still connected to the network) but I don't know if there's a similar structure on Macs.

**Comment by wblamkin** [comment]
Yes, it was an issue with the networking on my end. I assumed any computer connected to the internet could connect to any other computer with internet connection. All I had to do to get them working was put both computers on the same network.
