### ISSUE TITLE
.degrade() -> `AttributeError: 'PwRand' object has no attribute 'choice'

### ISSUE THREAD

**Issue by zbdm** [Qirky/Troop#15]
using Troop 0.6, FoxDot 0.7.9, SC 3.9.3, Python 3.7, Windows10.

with `z2 >> blip().degrade()` I've got an error: 
 
`AttributeError: 'PwRand' object has no attribute 'choice'`

BTW, how do you copy/paste in the Troop log window ? Ctrl+c  and Edit\Copy doesn't work

**Comment by Qirky** [comment]
Strange, I was confident that issue with FoxDot was fixed - could you run `print(__version__)` in Troop to confirm it's version 0.7.9? It seems that the copy/paste is only enabled for the text widget so I will add that to Troop this week

**Comment by zbdm** [comment]
my fault, I have 2 versions installed (git & pip), so I upgrade both to 0.7.9 and works fine.
Sorry. Have a lot of fun jamming with Troop.
