### ISSUE TITLE
Problem when highlight and replace one character

### ISSUE THREAD

**Issue by zbdm** [Qirky/Troop#17]
A strange problem when you highlight only a single character and try to replace it. It doesn't update on the self editor screen but it's ok for the others peers screens. 
Try on W10 with Python 3.7, same problem on an other laptop W10 Python 3.5.

Problem appears on the latest github version.
I try the 0.8.1 (zip & exe) release and it works fine.

**Comment by Qirky** [comment]
Ahh I think it's because the combination of deleting 1 character and inserting 1 character is sort of like an operation  size of 0 it's not applying it locally so will look into that. Thanks for catching this!

**Comment by Qirky** [comment]
Should be fixed now!
