### ISSUE TITLE
can't start server (Mac) [Errno 8] nodename nor servername provided..

### ISSUE THREAD

**Issue by Chovin** [Qirky/Troop#2]
On Mac 10.12.6
When trying to `python run-server.py`, I get
```
Traceback (most recent call last):
  File "run-server.py", line 26, in <module>
    myServer = TroopServer(log = "--log" in sys.argv)
  File "/Users/Chovin/Projects/LiveCoding/Troop/src/server.py", line 53, in __init__
    for info in socket.getaddrinfo(socket.gethostname(), None):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

Any info would be appreciated.
I'll update the issue if I find anything.

**Comment by Qirky** [comment]
Hi Chovin, I've added a quick fix try/catch around that so should run ok but will print the hostname to the console as opposed to IP address. I think it's something to do with Python on Mac but hopefully I'll come across a better solution in future

**Comment by Chovin** [comment]
Does seem to be a Mac related thing on new versions. Thanks for the fix!
