### ISSUE TITLE
[0.9.1] Foxdot Interpreter crash

### ISSUE THREAD

**Issue by CrashServer** [Qirky/Troop#22]
When I run Troop with the FoxDot Interpreter, I've got this error but looks good with Tidal & SC: 

```File "C:\Users\sebas\Troop\src\interpreter.py", line 186, in start
    if self.bootstrap is not None:
AttributeError: 'FoxDotInterpreter' object has no attribute 'bootstrap'
```

I quick fix it with a ```bootstrap = None``` on line 131 from interpreter.py and no more errors. 
Next time I try to make PR.

**Comment by Qirky** [comment]
Thanks for the catch! Fixed now :)
