### ISSUE TITLE
[Errno 61] Connection Refused

### ISSUE THREAD

**Issue by RanggaPAji** [Qirky/Troop#24]
Hi! i'm excited to try Troop for the first time. I did the installation like the instruction, but when i tried to start the client i'm getting the "[Errno 61] Connection Refused". I tried using the `python3 run-client.py --mode TidalCycles` and `python run-client.py --mode TidalCycles` but the issues are still the same. Tried with the Sonic Pi and SuperCollider and still didn't work. I've been thinking is it because i only use one laptop or there's no problem with it. i'm no programmer, but i love to creating music using all these software and want to learn about it more. so when i read about Troop, i'm super excited. I'm using Mac when i tried the Troop.
thanks and all the best!

* I attached the screenshot from the Troop client.
<img width="1080" alt="Screen Shot 2019-05-03 at 16 04 52" src="https://user-images.githubusercontent.com/37600867/57128775-b2a6cb00-6dbe-11e9-923b-8773fe783b41.png">

**Comment by Qirky** [comment]
Have you started the server application first? If not, you'll need to run `python run-server.py` in a separate terminal window and enter a password. Then you can connect multiple client programs to the server

**Comment by RanggaPAji** [comment]
ahhh yes. i tried it and it worked!!! but at the first time the interface
got freezed. and then i restarted and i could play the TidalCycles. Thank
you very much!

**Comment by RanggaPAji** [comment]
all the best for you Ryan!

**Comment by Qirky** [comment]
Great stuff - let me know if it starts freezing / crashing at all
