### ISSUE TITLE
Can't connect when trying to join abroad server

### ISSUE THREAD

**Issue by RanggaPAji** [Qirky/Troop#29]
Hi, so i currently living in Yogyakarta. Me and some of my friends in Argentina wanted to start an online livecoding session with Troop. One of my friend stand as the server, and when i tried to connect to his IP i couldn't connect and got this:

![error Troop](https://user-images.githubusercontent.com/37600867/66095707-bb483b00-e5c2-11e9-9857-53688e387a61.jpg)

is this maybe also because of an IP issue?

**Comment by Qirky** [comment]
Where is the server being hosted? If it's on your friends laptop in Argentina then you won't be able to connect to it directly. You'll have to host the server program on a publicly accessible server, such as at a data center, and make sure the firewall allows the correct ports to be open. Sorry about that! I am thinking of adding a publicly accessible service at some point but in the mean time I'll try and add some docs on how to set up a public server to use troop.

**Comment by RanggaPAji** [comment]
It's hosted on my friend's laptop in Argentina. Ahhh i see, so it's a bit complicated i think. No it's totally fine man. thank you so much for this answer and explanation. Good luck and all the best for you!
