### ISSUE TITLE
Crashing on tidal error

### ISSUE THREAD

**Issue by yaxu** [Qirky/Troop#37]
On latest OT branch under linux, I'm finding certain Tidal errors result in Troop crashing.

E.g. this syntax error:
```
d1 $ every 2 sound "bd"
```
Results in this in the troop post window:
```
[Errno 32] Broken pipe
"Can't connect to server"
```
and this on the console:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alex/src/Troop/src/receiver.py", line 93, in handle
    raise(e)
EmptyMessageError: 'Message contained no data'
```

**Comment by yaxu** [comment]
Things seem happier under python 3, no crashes. I do see some strangeness in the output buffer though which might be related:
![image](https://user-images.githubusercontent.com/27940/74377109-37595780-4ddb-11ea-9572-7da9830f81a8.png)

**Comment by Qirky** [comment]
Very strange, I'll have to get my raspberry pi out to test this so might not be until the weekend I'm afraid

**Comment by ryan-kirkb** [comment]
Ok, so it's taking me month to get linux installed. Does this only happen with Tidal any other mode?

**Comment by Qirky** [comment]
I do get some strange character issues but generally fine with Python 3 on Ubuntu - dropping support for Python 2 anyway but it's probably due to the very hacky way I'm reading from the stdout but there doesn't seem to be a very good way either

**Comment by yaxu** [comment]
Yep Python 3 is the future !
