### ISSUE TITLE
is there a non-GUI client?

### ISSUE THREAD

**Issue by jwaldmann** [Qirky/Troop#49]
Hi.

I found out about Troop via https://forum.toplap.org/t/what-is-this-editor-for-live-collaboration/1224 .

I wonder how would I get a setup like https://gitlab.imn.htwk-leipzig.de/waldmann/computer-mu/-/blob/master/tidal/code/COLLAB.md

It seems to me that I should want to run a Troop client on the computer that does the audio rendering (i.e., that runs tidal, supercollider, and the streaming server).

But that computer is remote (I go there via ssh) and I don't want a client with a GUI there. 

I could perhaps do the audio rendering locally and stream to the remote server but that would add extra latency. Hm.

**Comment by Qirky** [comment]
Hi there, it's only accessible via the GUI I'm afraid
