### ISSUE TITLE
how to exit the client?

### ISSUE THREAD

**Issue by jwaldmann** [Qirky/Troop#51]
Is there a way to gracefully exit the GUI client? I cat hit Ctrl-C a few times in the console but that feels wrong. Microsoft taught the world  to expect the "Quit" action in the "File" menu ...

**Comment by Qirky** [comment]
Is there not an 'X' to close the window? Windows, Mac, and several Linux OS's I have tested it on all have an 'X' for closing the window

**Comment by jwaldmann** [comment]
perhaps I am missing window decorations since I'm using https://xmonad.org/ ?

**Comment by Qirky** [comment]
Add 'exit' to menu
