### ISSUE TITLE
feed back information from client?

### ISSUE THREAD

**Issue by jwaldmann** [Qirky/Troop#53]
the REAMDE says this for the "multiple instances":

> When the "master" laptop receives text in the console, 
> it is sent to all of the other users so you can see exactly what your code is doing.

Well, sort of. I see the command that's being sent, but not the machine's (tidalcycles) answer (*) If the answer is an error message, it would be important to know. Else, you're left guessing why the pattern you hear didn't change, while the text you edit, did.

(*) or do I? sometimes I don't. Is there some option for this?

**Comment by Qirky** [comment]
It's probably to do with how Tidal is handling `stderr` output - this works as expected using FoxDot as both `stdout` and `stderr` are printed for all connected clients with the `-m none` flag. The (*) part of your answer indicates that this is inconsistent and you *do* see it sometimes?

**Comment by jwaldmann** [comment]
Hi. Thanks for responding. I will re-run some experiments. 

My use case was that just one client is running Tidal, and others are None (because they get the audio stream). Then I'd hope that all see stdout/err of the unique Tidal client. 

But this can't work in general? What is the expected behaviour if, say, two clients connect with mode Tidal, and three with mode None?

**Comment by Qirky** [comment]
This works as expected on Windows and Ubuntu 18.04. One master client running tidal and multiple others with 'none', which all receive stderr output from tidal.

With multiple clients running Tidal, then the first connected is the 'master'

**Comment by jwaldmann** [comment]
OK confirm that this works. Sorry for confusion.
