### ISSUE TITLE
Feature request: Evaluate multi-line selection

### ISSUE THREAD

**Issue by Sohalt** [Qirky/Troop#60]
It would be cool to be able to evaluate all currently selected lines. This would be especially helpful when collaborating with multiple people on a single Sonic Pi file, because it would allow selectively making changes to individual live_loops without having to wait for everyone to get their code to a safe state.

**Comment by Qirky** [comment]
I've added a multi-line selection evaluate but will evaluate all the lines the selection is on, not just the selected text :+1:

**Comment by Sohalt** [comment]
Cool! Thank you!
